### ISSUE TITLE
ERROR: No matching distribution found for opencv-python (from checkerboard)

### ISSUE THREAD

**Issue by JavierClearImageAI** [lambdaloop/checkerboard#2]
Great Job!
It works fine in my laptop, but I get the next message when installing in my remote machine:

> *ERROR: Could not find a version that satisfies the requirement opencv-python (from checkerboard) (from versions: none)
ERROR: No matching distribution found for opencv-python (from checkerboard)*.

Do you know which open-CV version dependency do I need?

Thanks a lot

**Comment by JavierClearImageAI** [comment]
I sorted this out by cloning the repository from Githug, instead of doing "pip install checkerboard"

**Comment by lambdaloop** [comment]
Ah I see, I had both `opencv-python` and `opencv-contrib-python` as dependencies in setup.
I have pushed a fix to only require `opencv-python`
