### ISSUE TITLE
only working with pattern (9,6)

### ISSUE THREAD

**Issue by JavierClearImageAI** [lambdaloop/checkerboard#3]
corners_reshaped = corners[:, :2].reshape(*size, 2)
ValueError: cannot reshape array of size 108 into shape (15,10,2)

It seems to work only with a checkerboard of the shape (9,6). Is there a bug there? I'll try to fix it if I have time, but I would like to know if that could be possible in your opinion. I'll try first to get it with cv2, then to make this  one work with our checkerboard patterns.

Thanks

**Comment by simbamford** [comment]
I also see this issue. I've just submitted a PR that fixes it.

**Comment by lambdaloop** [comment]
Should be fixed by @simbamford 's PR #4
